{% set name = "gw-dsl-parser" %}
{% set version = "0.1.49.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/gw_dsl_parser-{{ version }}.tar.gz
  sha256: f0c086e4c1015355935b26ae471244523e9f5c2821c888fb9fe245252268a027

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - hatchling
    - pip
  run:
    - python
    - wasmtime-py >=12.0.0

test:
  imports:
    - gw_dsl_parser
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Kanaries/gw-dsl-parser-py
  summary: Convert your graphic-walker workflow to sql
  description: Convert your graphic-walker workflow to sql
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  dev_url: https://github.com/Kanaries/gw-dsl-parser-py
  doc_url: https://github.com/Kanaries/gw-dsl-parser-py

extra:
  recipe-maintainers:
    - longxiaofei
